In [7]:
import pandas as pd
import numpy as np

# Läs in kalkylarket som beskriver topografin
df = pd.read_excel("Topografi karta.xlsx", header=None)

# Konvertera direkt till en NumPy matrix
matrix = df.to_numpy()

print(matrix)
print(matrix.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [3 3 3 ... 0 0 0]
 [3 3 3 ... 0 0 0]
 [3 3 3 ... 0 0 0]]
(70, 140)


In [8]:
print(matrix[16, 13]) #2
print(matrix[19, 17]) #2
print(matrix[10, 15]) #1
print(matrix[6, 4])   #1
print(matrix[50, 33]) #3
print(matrix[5, 60])  #3
print(matrix[18, 66]) #1
print(matrix[51, 59]) #2

2
2
1
1
3
3
1
2
